### PR TITLE
Wipe the tape after connection is closed.

### PR DESCRIPTION
**Pull request by BlackDragon-B**
I always hate it when its loading/downloading the music and it already has shit on it that it plays that. This will wipe the tape so it doesnt play old music.

### CODE REVIEW

**Comment by Ale32bit** [comment]
That code has an incredible amount of useless peripheral calls.

**Comment by BlackDragon-B** [comment]
> That code has an incredible amount of useless peripheral calls.

Its the same code as the wipe code in the tape program.

**Comment by Luca0208** [comment]
> That code has an incredible amount of useless peripheral calls.

I second this. It does seem rather strange. Usually it should be enough to rewind by `-math.huge` then write it to the tape and then rewind again. I'm also confused as to why it's writing `0xAA` instead of `0x00`

**Comment by Luca0208** [comment]
I'm sorry but I'm not going to merge this. I'm trying to decrease the number of peripheral calls this takes and the wiping code uses quite a lot of unnecessary peripheral calls. I'd rather write a little wiping snippet myself than copy the one from computronics.

**Pull request closed without merging**
